# 通用的单数据库配置。

[alembic]
# 迁移脚本路径
script_location = alembic

# 用于生成迁移文件的模板
# file_template = %%(rev)s_%%(slug)s
file_template = %%(slug)s

# 渲染日期时使用的时区
# 同时用于迁移文件内容和文件名。
# 字符串值会传递给 dateutil.tz.gettz()。
# 留空则使用本地时间。
# timezone =

# 应用于以下字段的最大字符长度：
# "slug" 字段
#truncate_slug_length = 40

# 设置为 'true' 时，在以下命令期间运行环境：
# 'revision' 命令，无论是否自动生成。
# revision_environment = false

# 设置为 'true' 时，允许没有对应源码的 .pyc 和 .pyo 文件
# 在以下目录中被识别为迁移版本：
# versions/ 目录
# sourceless = false

# 迁移版本位置配置；默认位置为
# alembic/versions。使用多个迁移版本
# 目录时，初始版本必须通过 --version-path 指定。
# version_locations = %(here)s/bar %(here)s/bat alembic/versions

# 写入迁移版本文件时使用的输出编码
# 来源模板为 script.py.mako。
# output_encoding = utf-8

# 日志配置
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
